name: Code coverage summary report

on:
    workflow_dispatch: # Manually trigger the workflow

run-name: pan<C>akes<🥞> string coverage summary report

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Install gcovr
        run: pip3 install gcovr
      
      - name: Produce XML coverage
        run: make coverage_xml
      
      - name: Generate code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/xml/*.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: file
          thresholds: "60 80"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Add generated coverage report
          branch: assets
          title: Add generated coverage report
          body: This pull request adds the generated .md file to the repository
          labels: automated, coverage
          add-paths: |
            *.md
          token: ${{ secrets.GH_TOKEN }}
