name: Test code coverage summary report

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - "main"

run-name: pan<C>akes<🥞> string tests coverage summary report

jobs:
  code-coverage-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Install gcovr
        run: pip3 install gcovr
      
      - name: Produce XML coverage
        run: |
          make -j && ./build/result/test_exec
          make -j coverage_xml
      
      - name: Generate code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/xml/*.xml
          badge: true
          format: markdown
          output: both
          fail_below_min: true
          thresholds: "80 90"
