name: Test code coverage summary report

on:
    workflow_dispatch:

run-name: pan<C>akes<🥞> string tests coverage summary report

jobs:
  code-coverage-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: Install gcovr
        run: pip3 install gcovr
      
      - name: Produce XML coverage
        run: make coverage_xml
      
      - name: Generate code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/xml/*.xml
          badge: true
          format: markdown
          output: file
          fail_below_min: true

      - name: Insert report into README.md
        run: |
          mkdir -p assets/
          cp code-coverage-results.md assets/
          python3 .github/workflows/scripts/file_insert.py assets/code-coverage-results.md README.md "<!-- GENERATED COVERAGE START -->" "<!-- GENERATED COVERAGE END -->"
      
      - name: Add generated markdown to repository
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/code-coverage-results.md
          git add README.md
          git commit -m "Save generated coverage report & Add to README.md"
          git checkout 
          git push origin main
